### ISSUE TITLE
unknown attribute main

### ISSUE THREAD

**Issue by Darren120** [AmeddahAchraf/Food-Delivery-SwiftUI#1]
hi why am i getting unknown attribute main?

**Comment by Darren120** [comment]
are u using xcode developer beta?

**Comment by AmeddahAchraf** [comment]
yes, beta2

**Comment by Darren120** [comment]
Damn... can't use it then >.< do you have projects that works on the current Xcode ?

**Comment by AmeddahAchraf** [comment]
you can download Xcode beta without having Big sur
Download here : https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes
