### ISSUE TITLE
question

### ISSUE THREAD

**Issue by michelmelo** [AmeddahAchraf/Food-Delivery-SwiftUI#2]
if i made the api you will add to the project?

**Comment by AmeddahAchraf** [comment]
Yes, I'd be happy to

**Comment by onyekadev1** [comment]
Hi dear.. can i use android version dashboard as an api to make the ios work. That is this ios will be inly the client base

**Comment by shreya-jindal** [comment]
hey what is software you used to make this video of your app

**Comment by galeano1990** [comment]
Estoy interesado en el proyecto

**Comment by fatimh775** [comment]
كيف اخذ هذا اتطبيق واعدل علية

**Comment by galeano1990** [comment]
No le entiendo, puede escribir en inglés?
